import = [
  "~/.config/alacritty/theme.toml",
  "~/.config/alacritty/font.toml",
  "~/.config/alacritty/font-size.toml",
  "~/.local/share/omakub/defaults/alacritty.toml",
  "~/.config/alacrity/theme-catp.toml",
]

[window]
opacity = 1.0
